### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ethanholz** [lfurze/simple-bluesky-comment-embed-wp#1]
In the README, you note a license file but none exists. Would you be willing to add the license file to this repo?

**Comment by lfurze** [comment]
Thanks Ethan I’ll action this today

Leon


*Practical AI Strategies* is available now at Amba Press
<https://ambapress.com.au/products/practical-ai-strategies>

Educational Consultant and PhD Student
Practical Writing Strategies is out now from Amba Press
<https://ambapress.com.au/products/practicalwritingstrategies>
Non-Executive Director - Young Change Agents
<https://youngchangeagents.com/>
Non-Executive Director - Reframing Autism
<https://reframingautism.org.au/about-us/>
leonfurze.com

**Comment by ethanholz** [comment]
Thanks!
